name: 'Lifepixels SVG Generator'
description: 'Generates a GitHub-dark style pixel art SVG of an organism'
inputs:
  organism_query:
    description: 'Organism to search for (scientific names; e.g. "Canis lupus familiaris")'
    required: true
    default: 'Naja'
  output_path:
    description: 'Output file path for svg file'
    required: true
    default: './dist/organism.svg'
  grid_size:
    description: 'Grid size (g) for svg file. g X g (square)'
    required: false
    default: '30'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run Generator
      run: npx ts-node src/index.ts --query "${{ inputs.organism_query }}" --output "${{ inputs.output_path }}" --gridSize "${{ inputs.grid_size }}"
      shell: bash
      working-directory: ${{ github.action_path }}
